services:
  postgres:
    image: postgres:16-alpine
    container_name: webhook_inbox_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webhook_inbox
    ports:
      - "5432:5432"
    volumes:
      - pgdata_wi:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webhook_inbox || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 30

  backend:
    build: ./backend
    container_name: webhook_inbox_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_ADDR: ":8080"
      PUBLIC_BASE_URL: "http://localhost:8080"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/webhook_inbox?sslmode=disable"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata_wi:
